"""add_multi_problem_columns

Revision ID: 689f2dbf6ac7
Revises: 3ad67c4dc4ed
Create Date: 2026-07-04 15:47:03.354288
"""

from alembic import op
import sqlalchemy as sa



revision = '689f2dbf6ac7'
down_revision = '3ad67c4dc4ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS battles (
            id UUID PRIMARY KEY,
            host_username VARCHAR(50) NOT NULL,
            max_players INTEGER NOT NULL DEFAULT 2,
            time_limit INTEGER NOT NULL DEFAULT 15,
            problem_source VARCHAR(20) NOT NULL DEFAULT 'catalog',
            selected_slug VARCHAR(100),
            custom_problem TEXT,
            problem_id UUID REFERENCES problems(id) ON DELETE SET NULL,
            selected_slugs TEXT,
            custom_problems TEXT,
            problem_ids TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            start_time TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS battle_players (
            id UUID PRIMARY KEY,
            battle_id UUID NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
            player_index INTEGER NOT NULL,
            username VARCHAR(50) NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT FALSE,
            last_active TIMESTAMP WITH TIME ZONE,
            score INTEGER NOT NULL DEFAULT 0,
            solved BOOLEAN NOT NULL DEFAULT FALSE,
            solved_at TIMESTAMP WITH TIME ZONE,
            attempts INTEGER NOT NULL DEFAULT 0,
            code TEXT,
            lang VARCHAR(20) NOT NULL DEFAULT 'cpp',
            progress TEXT,
            active_problem_index INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS battle_history (
            id UUID PRIMARY KEY,
            battle_id UUID NOT NULL UNIQUE,
            problem_title VARCHAR(200),
            participants TEXT,
            winner VARCHAR(50),
            final_scores TEXT,
            problems_solved TEXT,
            points_earned TEXT,
            attempts TEXT,
            start_time TIMESTAMP WITH TIME ZONE,
            end_time TIMESTAMP WITH TIME ZONE,
            duration INTEGER,
            status VARCHAR(20) NOT NULL DEFAULT 'finished',
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        );
    """)
    op.execute("ALTER TABLE battle_players ADD COLUMN IF NOT EXISTS progress TEXT;")
    op.execute("ALTER TABLE battle_players ADD COLUMN IF NOT EXISTS active_problem_index INTEGER NOT NULL DEFAULT 0;")
    op.execute("ALTER TABLE battles ADD COLUMN IF NOT EXISTS selected_slugs TEXT;")
    op.execute("ALTER TABLE battles ADD COLUMN IF NOT EXISTS custom_problems TEXT;")
    op.execute("ALTER TABLE battles ADD COLUMN IF NOT EXISTS problem_ids TEXT;")
    op.execute("ALTER TABLE submissions ADD COLUMN IF NOT EXISTS battle_id UUID REFERENCES battles(id) ON DELETE CASCADE;")
    op.execute("CREATE INDEX IF NOT EXISTS ix_submissions_battle_id ON submissions(battle_id);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'problem_ids')
    op.drop_column('battles', 'custom_problems')
    op.drop_column('battles', 'selected_slugs')
    op.drop_column('battle_players', 'active_problem_index')
    op.drop_column('battle_players', 'progress')
    # ### end Alembic commands ###
